[
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "ramalakshmi",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "ramalakshmi",
    "AccountNumber": "1006",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "cbn",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "cbn",
    "AccountNumber": "1007",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "909044"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "user1003",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "user1003",
    "AccountNumber": "1003",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "007"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "user1004",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "user1004",
    "AccountNumber": "1004",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "ramalakshmi",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "ramalakshmi",
    "AccountNumber": "1006",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "cbn",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "cbn",
    "AccountNumber": "1007",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "909044"
  },
  {
    "Ownership": "Private",
    "BillingCity": "banglore",
    "accountName__c": null,
    "Rating": "Warm",
    "status__c": "false",
    "type": "Account",
    "Name": "vamsi",
    "AccountNumber": "77878799",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40000.0",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "G.mahesh",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "G.mahesh",
    "AccountNumber": "1004",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "sushila",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "sushila",
    "AccountNumber": "1005",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "user1003",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "user1003",
    "AccountNumber": "1003",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "007"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "user1004",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "user1004",
    "AccountNumber": "1004",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": null,
    "BillingCity": null,
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "vamsi",
    "AccountNumber": null,
    "Industry": null,
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "remo",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "remo",
    "AccountNumber": "1008",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "007"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "shoban",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "shoban",
    "AccountNumber": "1009",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "mukeshvarma",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "mukeshvarma",
    "AccountNumber": "1010",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "007"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "rao ramesh",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "rao ramesh",
    "AccountNumber": "1011",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "G.mahesh",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "G.mahesh",
    "AccountNumber": "1004",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "sushila",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "sushila",
    "AccountNumber": "1005",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": null,
    "BillingCity": null,
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "Sample Account for Entitlements",
    "AccountNumber": null,
    "Industry": null,
    "Type": null,
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "rgv",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "rgv",
    "AccountNumber": "1000",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "kamala",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "kamala",
    "AccountNumber": "1001",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "909044"
  },
  {
    "Ownership": "Private",
    "BillingCity": "CIty1001",
    "accountName__c": "USER1001",
    "Rating": "Rate1001",
    "status__c": "true",
    "type": "Account",
    "Name": "USER1001",
    "AccountNumber": "1001",
    "Industry": "Banking1001",
    "Type": "Customer - Direct1001",
    "Id": null,
    "AnnualRevenue": "1001.0",
    "phoneNumber__c": "1000001001"
  },
  {
    "Ownership": "Private",
    "BillingCity": "CIty1002",
    "accountName__c": "USER1002",
    "Rating": "Rate1002",
    "status__c": "true",
    "type": "Account",
    "Name": "USER1002",
    "AccountNumber": "1002",
    "Industry": "Banking1001",
    "Type": "Customer - Direct1002",
    "Id": null,
    "AnnualRevenue": "1002.0",
    "phoneNumber__c": "1000001002"
  },
  {
    "Ownership": "Private",
    "BillingCity": "india",
    "accountName__c": "rajesh",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "rajesh",
    "AccountNumber": "1003",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "8005551212"
  },
  {
    "Ownership": "Private",
    "BillingCity": "india",
    "accountName__c": "gopal",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "gopal",
    "AccountNumber": "1002",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "909003344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "ramgopalvarma",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "ramgopalvarma",
    "AccountNumber": "1012",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "007"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "kathi Mahesh",
    "Rating": "Hot",
    "status__c": "true",
    "type": "Account",
    "Name": "kathi Mahesh",
    "AccountNumber": "1013",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "008"
  },
  {
    "Ownership": "Private",
    "BillingCity": "jmd",
    "accountName__c": "ramalakshmi",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "ramalakshmi",
    "AccountNumber": "1006",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "903344"
  },
  {
    "Ownership": "Private",
    "BillingCity": "pdtr",
    "accountName__c": "cbn",
    "Rating": "Hot",
    "status__c": "false",
    "type": "Account",
    "Name": "cbn",
    "AccountNumber": "1007",
    "Industry": "Banking",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "40.0",
    "phoneNumber__c": "909044"
  },
  {
    "Ownership": "Public",
    "BillingCity": "Austin",
    "accountName__c": null,
    "Rating": "Hot",
    "status__c": null,
    "type": "Account",
    "Name": "Edge Communications",
    "AccountNumber": "CD451796",
    "Industry": "Electronics",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "1.39E8",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "Burlington",
    "accountName__c": null,
    "Rating": "Warm",
    "status__c": null,
    "type": "Account",
    "Name": "Burlington Textiles Corp of America",
    "AccountNumber": "CD656092",
    "Industry": "Apparel",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "3.5E8",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "Paris",
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "Pyramid Construction Inc.",
    "AccountNumber": "CC213425",
    "Industry": "Construction",
    "Type": "Customer - Channel",
    "Id": null,
    "AnnualRevenue": "9.5E8",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Private",
    "BillingCity": "Lawrence",
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "Dickenson plc",
    "AccountNumber": "CC634267",
    "Industry": "Consulting",
    "Type": "Customer - Channel",
    "Id": null,
    "AnnualRevenue": "5.0E7",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "Chicago",
    "accountName__c": null,
    "Rating": "Warm",
    "status__c": null,
    "type": "Account",
    "Name": "Grand Hotels & Resorts Ltd",
    "AccountNumber": "CD439877",
    "Industry": "Hospitality",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "5.0E8",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "New York",
    "accountName__c": null,
    "Rating": "Hot",
    "status__c": null,
    "type": "Account",
    "Name": "United Oil & Gas Corp.",
    "AccountNumber": "CD355118",
    "Industry": "Energy",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": "5.6E9",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "Portland",
    "accountName__c": null,
    "Rating": "Cold",
    "status__c": null,
    "type": "Account",
    "Name": "Express Logistics and Transport",
    "AccountNumber": "CC947211",
    "Industry": "Transportation",
    "Type": "Customer - Channel",
    "Id": null,
    "AnnualRevenue": "9.5E8",
    "phoneNumber__c": null
  },
  {
    "Ownership": "Other",
    "BillingCity": "Tucson",
    "accountName__c": null,
    "Rating": "Warm",
    "status__c": null,
    "type": "Account",
    "Name": "University of Arizona",
    "AccountNumber": "CD736025",
    "Industry": "Education",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": null,
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "United Oil & Gas, UK",
    "AccountNumber": "CD355119-A",
    "Industry": "Energy",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  },
  {
    "Ownership": "Public",
    "BillingCity": "Singapore",
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "United Oil & Gas, Singapore",
    "AccountNumber": "CD355120-B",
    "Industry": "Energy",
    "Type": "Customer - Direct",
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  },
  {
    "Ownership": "Private",
    "BillingCity": "Mountain View",
    "accountName__c": null,
    "Rating": "Cold",
    "status__c": null,
    "type": "Account",
    "Name": "GenePoint",
    "AccountNumber": "CC978213",
    "Industry": "Biotechnology",
    "Type": "Customer - Channel",
    "Id": null,
    "AnnualRevenue": "3.0E7",
    "phoneNumber__c": null
  },
  {
    "Ownership": null,
    "BillingCity": "San Francisco",
    "accountName__c": null,
    "Rating": null,
    "status__c": null,
    "type": "Account",
    "Name": "sForce",
    "AccountNumber": null,
    "Industry": null,
    "Type": null,
    "Id": null,
    "AnnualRevenue": null,
    "phoneNumber__c": null
  }
]