#%RAML 1.0 Library
traits:
  status: !include ../exchange_modules/ef6ef77f-c721-4104-86ec-5714bb5f4e90/common-accounts-fragments/1.0.6/traits/querystatus-trait.raml
  accountnumber: !include ../exchange_modules/ef6ef77f-c721-4104-86ec-5714bb5f4e90/common-accounts-fragments/1.0.6/traits/queryAccountNumber-trait.raml