{
  "accountRequest": [
    {
      "Name": "ramalakshmi",
      "AccountNumber": "1006",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "cbn",
      "AccountNumber": "1007",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "909044",
      "Ownership": "Private"
    },
    {
      "Name": "user1003",
      "AccountNumber": "1003",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "007",
      "Ownership": "Private"
    },
    {
      "Name": "user1004",
      "AccountNumber": "1004",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "ramalakshmi",
      "AccountNumber": "1006",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "cbn",
      "AccountNumber": "1007",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "909044",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": "77878799",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40000.0",
      "status": "false",
      "BillingCity": "banglore",
      "Rating": "Warm",
      "phone": "",
      "Ownership": "Private"
    },
    {
      "Name": "G.mahesh",
      "AccountNumber": "1004",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "sushila",
      "AccountNumber": "1005",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "user1003",
      "AccountNumber": "1003",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "007",
      "Ownership": "Private"
    },
    {
      "Name": "user1004",
      "AccountNumber": "1004",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": null,
      "Type": "Customer - Direct",
      "Industry": null,
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": null,
      "Rating": null,
      "phone": "",
      "Ownership": null
    },
    {
      "Name": "remo",
      "AccountNumber": "1008",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "007",
      "Ownership": "Private"
    },
    {
      "Name": "shoban",
      "AccountNumber": "1009",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "mukeshvarma",
      "AccountNumber": "1010",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "007",
      "Ownership": "Private"
    },
    {
      "Name": "rao ramesh",
      "AccountNumber": "1011",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "G.mahesh",
      "AccountNumber": "1004",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "sushila",
      "AccountNumber": "1005",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": null,
      "Type": null,
      "Industry": null,
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": null,
      "Rating": null,
      "phone": "",
      "Ownership": null
    },
    {
      "Name": "rgv",
      "AccountNumber": "1000",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "kamala",
      "AccountNumber": "1001",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "909044",
      "Ownership": "Private"
    },
    {
      "Name": "USER1001",
      "AccountNumber": "1001",
      "Type": "Customer - Direct1001",
      "Industry": "Banking1001",
      "AnnualRevenue": "1001.0",
      "status": "true",
      "BillingCity": "CIty1001",
      "Rating": "Rate1001",
      "phone": "1000001001",
      "Ownership": "Private"
    },
    {
      "Name": "USER1002",
      "AccountNumber": "1002",
      "Type": "Customer - Direct1002",
      "Industry": "Banking1001",
      "AnnualRevenue": "1002.0",
      "status": "true",
      "BillingCity": "CIty1002",
      "Rating": "Rate1002",
      "phone": "1000001002",
      "Ownership": "Private"
    },
    {
      "Name": "rajesh",
      "AccountNumber": "1003",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "india",
      "Rating": "Hot",
      "phone": "8005551212",
      "Ownership": "Private"
    },
    {
      "Name": "gopal",
      "AccountNumber": "1002",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "india",
      "Rating": "Hot",
      "phone": "909003344",
      "Ownership": "Private"
    },
    {
      "Name": "ramgopalvarma",
      "AccountNumber": "1012",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "007",
      "Ownership": "Private"
    },
    {
      "Name": "kathi Mahesh",
      "AccountNumber": "1013",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "true",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "008",
      "Ownership": "Private"
    },
    {
      "Name": "ramalakshmi",
      "AccountNumber": "1006",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "jmd",
      "Rating": "Hot",
      "phone": "903344",
      "Ownership": "Private"
    },
    {
      "Name": "cbn",
      "AccountNumber": "1007",
      "Type": "Customer - Direct",
      "Industry": "Banking",
      "AnnualRevenue": "40.0",
      "status": "false",
      "BillingCity": "pdtr",
      "Rating": "Hot",
      "phone": "909044",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": "CD451796",
      "Type": "Customer - Direct",
      "Industry": "Electronics",
      "AnnualRevenue": "1.39E8",
      "status": null,
      "BillingCity": "Austin",
      "Rating": "Hot",
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CD656092",
      "Type": "Customer - Direct",
      "Industry": "Apparel",
      "AnnualRevenue": "3.5E8",
      "status": null,
      "BillingCity": "Burlington",
      "Rating": "Warm",
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CC213425",
      "Type": "Customer - Channel",
      "Industry": "Construction",
      "AnnualRevenue": "9.5E8",
      "status": null,
      "BillingCity": "Paris",
      "Rating": null,
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CC634267",
      "Type": "Customer - Channel",
      "Industry": "Consulting",
      "AnnualRevenue": "5.0E7",
      "status": null,
      "BillingCity": "Lawrence",
      "Rating": null,
      "phone": "",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": "CD439877",
      "Type": "Customer - Direct",
      "Industry": "Hospitality",
      "AnnualRevenue": "5.0E8",
      "status": null,
      "BillingCity": "Chicago",
      "Rating": "Warm",
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CD355118",
      "Type": "Customer - Direct",
      "Industry": "Energy",
      "AnnualRevenue": "5.6E9",
      "status": null,
      "BillingCity": "New York",
      "Rating": "Hot",
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CC947211",
      "Type": "Customer - Channel",
      "Industry": "Transportation",
      "AnnualRevenue": "9.5E8",
      "status": null,
      "BillingCity": "Portland",
      "Rating": "Cold",
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CD736025",
      "Type": "Customer - Direct",
      "Industry": "Education",
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": "Tucson",
      "Rating": "Warm",
      "phone": "",
      "Ownership": "Other"
    },
    {
      "Name": "",
      "AccountNumber": "CD355119-A",
      "Type": "Customer - Direct",
      "Industry": "Energy",
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": null,
      "Rating": null,
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CD355120-B",
      "Type": "Customer - Direct",
      "Industry": "Energy",
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": "Singapore",
      "Rating": null,
      "phone": "",
      "Ownership": "Public"
    },
    {
      "Name": "",
      "AccountNumber": "CC978213",
      "Type": "Customer - Channel",
      "Industry": "Biotechnology",
      "AnnualRevenue": "3.0E7",
      "status": null,
      "BillingCity": "Mountain View",
      "Rating": "Cold",
      "phone": "",
      "Ownership": "Private"
    },
    {
      "Name": "",
      "AccountNumber": null,
      "Type": null,
      "Industry": null,
      "AnnualRevenue": 0,
      "status": null,
      "BillingCity": "San Francisco",
      "Rating": null,
      "phone": "",
      "Ownership": null
    }
  ]
}