{
  "headers": {
    "transactionid": "nbjfho84tuyy96",
    "clientid": "878898798hgu7868yyh",
    "clientsecret": "9yujfyurybjsddiu9394jj",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.10",
    "accept": "*/*",
    "postman-token": "47d5e50a-1e88-4681-99b4-44d35c0309f8",
    "host": "0.0.0.0:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "778"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/accounts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/accounts",
  "listenerPath": "/api/*",
  "relativePath": "/api/accounts",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/accounts",
  "rawRequestPath": "/api/accounts",
  "remoteAddress": "/127.0.0.1:56093",
  "requestPath": "/api/accounts"
}